#!/bin/bash

##### VARIABLE ASSIGNMENT #####
##### DO NOT CHANGE THESE #####

BASE_DIR='/opt'
INSTALL_LOC='/opt/dvm'
CONFIG_DIR='/opt/dvm/configs'
CONFIG_REPO='https://github.com/Centrunk/centrunk-base-config'
CONFIG_FILE="$INSTALL_LOC/config.centrunk.yml"
VAULT_DL_URL="https://releases.hashicorp.com/vault/1.10.0/"
MC_DL_URL="https://dl.min.io/server/minio/release/"
MINIO_URL="https://104.248.50.158:9000"
export VAULT_ADDR='https://10.147.17.134:8200'

write_log_event()
{
  echo "[LOG]: " $(date +"%Y-%m-%d_%H-%M-%S")": $1" >> /var/log/centrunk_install.log
  echo $1
}

write_debug()
{
  echo "[DEBUG]: " $(date +"%Y-%m-%d_%H-%M-%S")": $1" >> /var/log/centrunk_install.log
}

write_stderr()
{
  echo "[STDERR]: " $(date +"%Y-%m-%d_%H-%M-%S")": $1" >> /var/log/centrunk_install.log

}

pistar_cmds()
{
  ## FIX PISTAR'S SHITTY CODE
  grep -qxF "$FW_RULE_PISTAR_VAULT" /root/ipv4.fw || echo "$FW_RULE_PISTAR_VAULT" >> /root/ipv4.fw
  grep -qxF "$FW_RULE_PISTAR_MINIO" /root/ipv4.fw || echo "$FW_RULE_PISTAR_MINIO" >> /root/ipv4.fw
  /usr/local/sbin/pistar-firewall
}

upload_because_mc_sux()
{
  bucket=configs
  file=$1

  host=$MINIO_URL

  MINIO_CREDS=$(/opt/centrunk/vault kv get -format=json kv-v2/minio/cpe/cpe_$response | jq -r '.data.data')

  s3_key=$(echo $MINIO_CREDS | jq -r '.USERNAME')
  s3_secret=$(echo $MINIO_CREDS | jq -r '.SECRET')

  resource="/${bucket}/${file}"
  content_type="application/octet-stream"
  date=`date -R`
  _signature="PUT\n\n${content_type}\n${date}\n${resource}"
  signature=`echo -en ${_signature} | openssl sha1 -hmac ${s3_secret} -binary | base64`

  curl -X PUT -T "${file}" \
            -H "Host: ${host}" \
            -H "Date: ${date}" \
            -H "Content-Type: ${content_type}" \
            -H "Authorization: AWS ${s3_key}:${signature}" \
            $MINIO_URL${resource}
}

download_because_mc_sux()
{
  URL=$MINIO_URL
  MINIO_CREDS=$(/opt/centrunk/vault kv get -format=json kv-v2/minio/cpe/cpe_$response | jq -r '.data.data')
  USERNAME=$(echo $MINIO_CREDS | jq -r '.USERNAME')
  PASSWORD=$(echo $MINIO_CREDS | jq -r '.SECRET')
  BUCKET=configs
  MINIO_PATH="/${BUCKET}/$1"
  OUT_FILE=$2

  # Static Vars
  DATE=$(date -R --utc)
  CONTENT_TYPE='application/zstd'
  SIG_STRING="GET\n\n${CONTENT_TYPE}\n${DATE}\n${MINIO_PATH}"
  SIGNATURE=`echo -en ${SIG_STRING} | openssl sha1 -hmac ${PASSWORD} -binary | base64`

  curl -o "${OUT_FILE}" \
      -H "Host: $URL" \
      -H "Date: ${DATE}" \
      -H "Content-Type: ${CONTENT_TYPE}" \
      -H "Authorization: AWS ${USERNAME}:${SIGNATURE}" \
      $URL${MINIO_PATH}
}

###############################
###############################
###############################
###############################
###############################
###############################

# THE SCRIPT STARTS HERE

# check to see that we are root

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root or a user with sudo permissions. Please try again..." 
   exit 1
fi

# check to make sure we're working with a tech currently

echo "This installer should *only* be run while either dialed in with a Centrunk Technician or while on chat with one as well."
echo "Any other usage of this script is ENTIRELY UNSUPPORTED AND YOU ARE DOING SO AT YOUR OWN RISK."

# preflight checks for supported OSes

#check if we're on the centrunk distro
MACH_ID=$(cat /etc/machine-id)

if [[ -f /etc/centrunk-distro ]]
then
  # check for the default Centrunk Machine ID
  # if we find it, regnereate it 
  if [[ "$MACH_ID" == "b1df0844ab494f14b55bca43663f1535" ]]
  then
    rm /etc/machine-id
    systemd-machine-id-setup
    write_log_event "Detected Centrunk Distro, regnerated machine ID..."
    MACH_ID=$(cat /etc/machine-id)
  fi
  else
    echo "###################################################"
    echo "Please give Centrunk Tech Support this ID number: "
    echo "cpe_$(cat /etc/machine-id)"
    echo "###################################################"
    read -p "Press Enter to continue..." whatever
fi

DISTRO=$(cat /etc/os-release | grep "ID=" | grep -v "VERSION_ID")

case $DISTRO in
  ID=raspbian)
    # check if we are on pi-star, if so fixup the firewall
    PISTAR_CHECK=$(cat /etc/passwd | grep pi-star)
    if [[ -z $PISTAR_CHECK ]]
    then
      echo "Pi-Star detected. Pi-Star is no longer supported. Either install a supported distro below or the Centrunk Distro.
      [*] Debian
      [*] Ubuntu
      [*] Raspbian"
    exit 21
    fi
    echo "If you haven't already, please remember to change your password for the pi user. 
    You can do this by running \"passwd\" when this script is finished."
  ;;
  ID=ubuntu)
  ;;
  ID=debian)
  ;;
  *)
    echo "Unsupported distro. Please use one of the following Linux distros:
    [*] Debian
    [*] Ubuntu
    [*] Raspbian"
    exit 21
esac

# preflight checks for arch
ARCH=$(uname -m)

case $ARCH in
  x86_64)
    VAULT_ZIP_FILE="vault_1.10.0_linux_amd64.zip"
    MC_BINARY="linux-amd64/minio"
    MINIO_MODE="mc"
  ;;
  i686)
    X64_CAPABLE=grep flags /proc/cpuinfo | grep " lm "
    if [[ ! -z $X64_CAPABLE ]]
    then
      if [[ ! -z $I_KNOW_WHAT_I_AM_DOING ]]
      then
        echo "Okay. I see that you \"know what you're doing\". Setting flags for 32bit and continuing..."
        VAULT_ZIP_FILE="vault_1.10.0_linux_386.zip"
        MINIO_MODE="curl"
      else
        echo "You are running a 32bit Operating System on a 64bit capable machine. "
        echo "If this was intended, please run the following command prior to running this script: "
        echo "export I_KNOW_WHAT_I_AM_DOING=1"
        echo ""
        echo "Otherwise, go reinstall this operating system with an x86_64 distribution. "
        exit 99
      fi 
    else
      echo "This system is only 32bit capable. Performance may be impacted. "
      echo "Pressing on anyway!"
    fi
  ;;
  arm*)
    VAULT_ZIP_FILE="vault_1.10.0_linux_arm.zip"
    MC_BINARY="linux-arm/minio"
    MINIO_MODE="mc"
  ;;
  ppc*)
    echo "Why are you putting Centrunk on a PowerPC? Do you hate yourself?"
    exit 69
  ;;
  *)
    echo "Unsupported architecture $ARCH. Please use one of the following architectures: "
    echo "[*] i686
    [*] x86_64
    [*] arm
    [*] arm64"
    exit 100
  ;;
esac

# download the binaries to the proper locations depending on architecture

# setup the environment to access vault secrets manager
write_log_event "Installing Vault..."
if [[ ! -f /opt/centrunk/vault ]]
then
  wget https://releases.hashicorp.com/vault/1.10.0/$VAULT_ZIP_FILE
  unzip $VAULT_ZIP_FILE -d /opt/centrunk && rm -rf $VAULT_ZIP_FILE
  chmod +x /opt/centrunk/vault
  echo "export VAULT_ADDR='$VAULT_ADDR'" >> /etc/profile
fi

# set up the environment for minio client
#set mc aliases to be able to do quick minio commands

if [[ "$MINIO_MODE" == "mc" ]]
then
  if [[ ! -f /opt/centrunk/mc ]]
  then
    wget  https://dl.min.io/client/mc/release/linux-arm/mc -O /opt/centrunk/mc
    chmod +x /opt/centrunk/mc
  fi
elif [[ "$MINIO_MODE" == "curl" ]]
then
  write_log_event "Native CM command is not supported on this architecture, defaulting to RESTful requests..."
fi

##### ZEROTIER BLOCK #####
write_log_event "Ensuring ZeroTier is installed..."
if [ -x "$(command -v zerotier-cli)" ]
then
  true   
else
    write_log_event "ZeroTier is not installed, installing now..."
    curl -s https://install.zerotier.com/ | bash
fi

#################
# PROMPTS       #
#################

# we no longer require the CPEID, as we generate it
response=$(cat /etc/machine-id)

read -p "Enter your Centrunk Entitlement ID (EID): " entitlement
read -p "Enter the ZeroTier Network ID (ZTNID): " ZEROTIER

if [[ -z $entitlement || -z $ZEROTIER ]]
then
  write_log_event "Invalid entries. Please run the script again..."
  exit 25
fi

I_DONT_CARE=$(zerotier-cli join $ZEROTIER)

# check if we're auth'd on ZeroTier

while true
do
  zerotier-cli info | grep -q "TUNNELED"
  if [[ $? -eq 0 ]]
  then
    write_log_event "We've been auth'd onto ZeroTier. Continuing the script."
    break
  else
    write_log_event "Waiting 10 seconds and then checking again...Press Ctrl+C to abort and quit..."
    sleep 10
  fi
done


# installing our certs
write_log_event "Installing Vault Certificates..."
mkdir /usr/share/ca-certificates/vault
echo "-----BEGIN CERTIFICATE-----
MIIDPjCCAiagAwIBAgIRAKzGuEk9JW9Iifz73U65W8gwDQYJKoZIhvcNAQELBQAw
NTEUMBIGA1UEChMLTG9nIENvdXJpZXIxHTAbBgNVBAMTFHZhdWx0LmNlbnRydW5r
LmxvY2FsMB4XDTIyMDQwODIyMDYzNloXDTMyMDQwNTIyMDYzNlowNTEUMBIGA1UE
ChMLTG9nIENvdXJpZXIxHTAbBgNVBAMTFHZhdWx0LmNlbnRydW5rLmxvY2FsMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA38eVxnFcUc4mpWqgmgk3r7ZT
nN4XGGrVzYtavInxmOwWzrI68Zd12tVWfHAJqXEiF4kHHvDgMq+qp0x/gYebywvV
26ogZ7gLDC50IblC1Ph2yUw7YY4a7QTNTgEgLZbi72ZzCBkUYv+gOyDZJb1kJtxG
R4oYzjT8jSlvx3KvT5ZNmtkoeHvUy/YPzROamQ2ugsOUl9pZpZKVd9DFMr0GkY/g
XwLjaTXXXuSsYz+Ru039FmFCQVebpLrjOrjWtSt8+owOKJ/PYuGsw5tn1DUhwqQL
FnHKB174dp4o4lAjpIuuC/ZM/7ZfQOi1zvQy2NnUjsqL+ZIiWr+t7waOWrcEGQID
AQABo0kwRzAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYD
VR0TAQH/BAUwAwEB/zAPBgNVHREECDAGhwQKkxGGMA0GCSqGSIb3DQEBCwUAA4IB
AQCCH5hCghxh9s1peMc+EOLEeQqfzl0vW/Owb36lQjdvvaC9HHi24Lzth/p8rBSp
ilDDPhL3ypkrQ4AjcRTG4Pk+Y9jcpWgnsEMLnXX+A+QgO2fAnmc2+dgQgyktfz5n
hxOqKvsA80SwhYrlXxx+ea1MxqQfGMeJBhNrjLUUuw4uG/s0zPAnAzcvI2voJBWM
oAyms5MJGCR/p17roHEfAF30PNDh9QmzLghKrjUwlyMsQasINVqo4LeOEJIqKUeZ
Rk7syOD86q8lj+kl1hzbKzxWfw6cvN41APl0gEXk1lNQsMV7LiINCj90lBBE6adC
UqEKj8x+NLuAl0aZ7v0XtE4Y
-----END CERTIFICATE-----" > /usr/share/ca-certificates/vault/vault-ca.crt
echo "vault/vault-ca.crt" >> /etc/ca-certificates.conf
update-ca-certificates

/opt/centrunk/vault login token=$entitlement 
write_log_event "Login to Vault successful."
if [[ "$MINIO_MODE" == "mc" ]]
then
  /opt/centrunk/mc alias set ccm $MINIO_URL $(/opt/centrunk/vault kv get -format=json kv-v2/minio/cpe/cpe_$response | jq -r '.data.data.USERNAME') $(/opt/centrunk/vault kv get -format=json kv-v2/minio/cpe/cpe_$response | jq -r '.data.data.SECRET')
  if [[ $? -ne 0 ]]
  then
    write_log_event "Error setting the ConfigManagement alias. Please contact your Centrunk Tech. "
    exit 28
  fi
fi

echo "Welcome to the Centrunk Installer." 
write_log_event "Beginning installation..."

# Equipment ID Number (EIN) is generated on the hotspot
# Entitlement ID Number (EID) is generated administratively and allows the hotspot to get secrets

# Fetch the config files given the CPE Activation Codes

write_log_event "Actually starting the install now!"
sleep 1
write_log_event "You may see a bunch of shit you may or may not recognize
Don't worry about it. It's the program installing and creating itself. Woo!"
sleep 3

if [[ -f /opt/dvm/config.centrunk.yml ]]
then
  write_log_event "Found an existing config file. Will send that to CM instead of rewriting..."

  # figure out which method we're gonna use to send to Minio

  if [[ "$MINIO_MODE" == "mc" ]]
  then
    /opt/centrunk/mc cp /opt/dvm/config.centrunk.yml ccm/configs/cpe_$response
  elif [[ "$MINIO_MODE" == "curl" ]]
  then
    cp /opt/dvm/config.centrunk.yml /tmp/cpe_$response
    upload_because_mc_sux /tmp/cpe_$response
  else
    echo "How'd you get here you sneaky fucker?"
    exit 120
  fi
else
  write_log_event "Downloading config from CM..."
  if [[ "$MINIO_MODE" == "mc" ]]
  then
    /opt/centrunk/mc cp ccm/configs/cpe_$response /opt/dvm/config.centrunk.yml
  elif [[ "$MINIO_MODE" == "curl" ]]
  then
    download_because_mc_sux ${response} /opt/dvm/config.centrunk.yml
  else
    echo "How'd you get here you sneaky fucker?"
    exit 120
  fi
fi

#install the unit file
write_log_event "Installing the Centrunk systemd Service..."

# yeeting the p25 service in favor of naming it centrunk <3
if [[ -f /etc/systemd/system/p25.service ]]
then
  systemctl stop p25.service
  systemctl disable p25.service
  rm -rf /etc/systemd/system/p25.service
  systemctl daemon-reload
fi

if [[ -f /etc/systemd/system/centrunk.service ]]
then
  systemctl stop centrunk.service
  systemctl disable centrunk.service
  rm -rf /etc/systemd/system/centrunk.service
  systemctl daemon-reload
fi
# get the lastest template repository

if [ -d $CONFIG_DIR ]
then
  rm -rf $CONFIG_DIR
fi
git clone $CONFIG_REPO $CONFIG_DIR
cp $CONFIG_DIR/p25.service /etc/systemd/system/centrunk.service
write_log_event "Updating permissions on the Service..."
chmod 664 /etc/systemd/system/centrunk.service
systemctl daemon-reload
write_log_event "Reloaded systemd..."
systemctl enable centrunk.service

# add a user called Centrunk for remote admin commands
# this is an optional feature that will not be automatically enabled and require deliberate user action to enable.

if [[ -f /opt/centrunk/enable-remote-admin ]]
then
  write_log_event "Remote admin has been enabled by the user."
  if id "centrunk" &>/dev/null; then
    true
  else
      useradd -m centrunk
  fi
  echo centrunk:$(/opt/centrunk/vault kv get -format=json kv-v2/cpe_admin | jq -r '.data.data.PASSWORD') | chpasswd -e
  # add the user to the sudoers group
  usermod -a -G sudo centrunk
fi

# patch our iden table
cat <<EOF > /opt/dvm/iden_table.dat
# ChId,Base Freq,Spacing (khz),Input Offset (mhz),Bandwidth (khz),<newline>
0,851006250,6.25,-45.000,12.5,
1,762006250,6.25,30.000,12.5,
15,935001250,6.25,-39.00000,12.5,
2,146000000,6.25,1.000,12.5,
3,450000000,6.25,5.000,12.5,
4,430000000,6.25,5.000,12.5,
EOF


# update permissions to dvmhost user
chown dvmhost:dvmhost /opt/dvm/*
chown dvmhost:dvmhost /opt/dvm

#output commands
write_log_event "!!!DVMhost install completed!!!"
sleep 2
write_log_event "Recommend rebooting your system now, as boot parameters need to take effect to be able to flash your DVM Board."
read -p "Would you like to reboot your system now? [Y/N]: " ui_reb

case $ui_reb in
  Y|y)
    write_log_event "Rebooting your system now..."
    sleep 2
    reboot
  ;;
  N|n)
    write_log_event "Not rebooting. Flashing DVM boards *will not work* until reboot."
  ;;
  *)
    write_log_event "Invalid input. Being safe and not rebooting..."
  ;;
esac
exit 0